config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
    # belongs_to :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]
  before_action :correct_user, only: %i[:edit, :update, :destroy]
  # before_action :correct_user, only: %i[edit update destroy]
  before_action :authenticate_user!

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to list_url(@list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "Item successfully deleted." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.lists.find_by(id: params[:id])
    redirect_to lists_path, notice: "You are not authorised to edit this item" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:from, :project, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <% link_to "Home", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "About", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Feedback board", lists_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>


    </ul>
  </div>
</nav>

<%# <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> %>

app/views/home/index.html.erb
<div class="container-md">
    <div class="card">
        <div class="card-body">
            <h1>Having one of <em>those</em> days at work?</h1>
            <p>Sometimes you feel like you can't quite get it right.</p>
            <p>This app is meant to give you a boost.</p>
            <h2>Instructions for use</h2>
            <p>First, you'll need to sign up for an account</p>
            <p>Then, when you get that great feedback — from a colleague, or your manager — log in, and record it in the feedback board on this app.</p>
            <p>Your board will automatically save your feedback, so you can come back and check it when you need a pick-me-up.</p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeedbackApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "home/navbar" %>

    <div class="container" data-turbo="false"><!-- Need this to stop Turbo throwing errors on form action -->
       
      <%= yield %>
      
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="card" style="width: 42rem">
  <div class="card-body">
    <div class="form-group">
      <div>
        <%= form.label :from, style: "display: block" %>
        <%= form.text_field :from, class:"form-control" %>
      </div>

      <div>
        <%= form.label :project, style: "display: block" %>
        <%= form.text_field :project, class:"form-control" %>
      </div>

      <div>
        <%= form.label :description, style: "display: block" %>
        <%= form.text_area :description, class:"form-control" %>
      </div>

      <div>
        <%= form.label :user_id, id: :list_user_id, style: "display: block" %>
        <%= form.number_field :user_id, value: current_user.id %>
      </div>

      <br/>
      <div>
        <%= form.submit "Submit", class: "btn btn-dark"%>
      </div>
    </div><!-- End form group -->
</div><!-- End card -->
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <div class="row">
     <div class="col">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">
            <strong>From:</strong>
            <%= list.from %>
          </h5>
          <hr/>
          <p>
            <strong>Project:</strong>
            <%= list.project %>
          </p>

          <p>
            <strong>Description:</strong>
            <%= list.description %>
          </p>

           <p>
            <%# <strong>User:</strong> %>
            <% list.user_id %>
          </p>

           <p>
            <strong>Timestamp:</strong>
            <%= list.created_at %>
          </p>
            
          <p>
            <% link_to "Show this list", list, class: "btn btn-secondary" %>
          </p>
          <%= link_to "Edit", edit_list_path(list), class: "btn btn-outline-secondary btn-sm" %>
          <%= button_to "Delete", (list), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm", form: {style: 'display:inline-block;'}%>
        </div><!-- End card body -->   
      </div><!-- End card -->
    </div><!-- End column -->  
  </div><!-- End row -->
    
</div><!-- End dom_id list -->

app/views/lists/edit.html.erb
<h1>Edit item</h1>

<%= render "form", list: @list %>

<br>

<div>
  <% link_to "Show this list", @list, class: "btn btn-secondary" %>
  <%= link_to "Back to all feedback", lists_path, class: "btn btn-dark" %>
</div>

app/views/lists/index.html.erb
<p style="color: #be76fc"><%= notice %></p>

<h1>Feedback board</h1>
<%= link_to "Add a new item", new_list_path, class: "btn btn-dark" %>
<div id="lists">
<!-- For info: To display cards as Boostrap Grid, it's necessary to loop through the items after the row is created -->
  <div class="row"><!-- Begins the row -->
    <% @lists.each do |list| %>
      <% if list.user_id == current_user.id %>
        <div class="col-sm-4"><!-- Need to add the column after the start of the loop to get the cards to align in columns -->

          <%= render list %>

        </div><!-- End col -->
      <% end %>
    <% end %>
  </div><!-- End row -->
</div>

app/views/lists/new.html.erb
<h1>Add a new item</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to your board", lists_path, class: "btn btn-dark" %>
</div>

app/views/lists/show.html.erb
<p style="color: #be76fc"><%= notice %></p>

<%= render @list %>

<div>
  <!-- <%= link_to "Edit item", edit_list_path(@list) %> -->
  <%= link_to "Back to all feedback", lists_path, class: "btn btn-dark" %>

  <% button_to "Delete", @list, method: :delete %>
</div>